version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8876:80
    container_name: app_nginx
    depends_on:
      - app

  app:
    container_name: app
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
        - db

  db:
    image: postgres:16
    restart: always
    environment:
        POSTGRES_PASSWORD: root
    ports:
        - 8101:5432
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    container_name: db
